spring:
  jpa:
    generate-ddl: 'true'
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: 'true'
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: 'true'
  datasource:
    url: jdbc:h2:file:./db.h2
    driverClassName: org.h2.Driver
